version: '3.7'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=nico.bodmer1@gmail.com
      - MAIL_PASSWORD=NalaTeddy13
      - SECRET_KEY=aaom torj swfi lcae
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'PCrei'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
